### Variables
@baseUrl = {{$dotenv BASE_URL}}
@contentType = application/json

### 1. Obtener todas los categorías
GET {{baseUrl}}/categorias
Content-Type: {{contentType}}

### 2. Obtener categoría por ID (existente)
GET {{baseUrl}}/categorias/3
Content-Type: {{contentType}}

### 6. Obtener categoría por ID (no existente)
GET {{baseUrl}}/categorias/999
Content-Type: {{contentType}}